### ISSUE TITLE
Mobile: List of devices is not available after log in

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#834] opened 2023-11-28 09:19 UTC
**Steps**
1. On your device open STF and log in with valid credentials 
2. Look on main page 

**Actual result** 
The device list is not displayed by default. To open we need to click on "Device" 
<img width="325" alt="Zrzut ekranu 2023-11-30 o 10 58 45" src="https://github.com/zebrunner/stf/assets/149781148/d2a43dfb-a5ab-43c7-a44b-643fdbfbbd36">

**Comment by amastej** [comment] 2023-11-28 09:55
Bug hard to reproduce. 
First we need to clear browser history, cookies and cache and delete the remembered password in the system

**Comment by vdelendik** [comment] 2024-03-15 17:46
@amastej, closing as won't fix. The root cause is changes delivered by Ignacio in cookies and local application storage.
in scope of the we plan to integrate for every new release notes as part of migration steps the recommendation to:
1. clear cache and cookies
2. clear application local storage and relogin

**Comment by vdelendik** [comment] 2024-05-20 11:36
let's test again. I suppose it is mobile view

**Closed by vdelendik** 2024-05-20 11:36 UTC
Labels: documentation

**Comment by dhreben** [comment] 2024-05-20 15:23
Fixed according https://github.com/zebrunner/stf/issues/944
