### ISSUE TITLE
System messages are not closed on iphones

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#316] opened 2022-01-18 17:41 UTC
Steps:

1.  Sign in to stf and open  iphone 8
2. Click on OK button on system message to close it

Actual result:The message is not closed
Expected: The message is closed
<img width="440" alt="Снимок экрана 2022-01-18 в 18 58 33" src="https://user-images.githubusercontent.com/32964663/149989804-6d2ac7bd-1b1b-4fcc-9eb1-23b649578d0f.png">

**Comment by vdelendik** [comment] 2022-01-20 21:02
https://stackoverflow.com/questions/70611599/call-to-tap-failed-an-unknown-server-side-error-occurred-original-error
seems to be appium + wda issue which is fixed in v1.22.2.

**Comment by vdelendik** [comment] 2022-01-21 11:12
confirmed that appium 1.22.2 works well with system alerts. changes might be tested on demo server where 1.22.2 is installed.
also submitted https://github.com/appium/appium-docker-android/issues/143 with a request to provide appium docker images for 1.22.2 to be able to incorporate it into the Linux agent part as well

**Comment by dhreben** [comment] 2022-01-21 13:04
Fixed after updated appium to 1.22.2

Tested on Iphone 8

**Comment by dhreben** [comment] 2022-05-12 13:41
Verified.

**Closed** 2022-05-12 13:41 UTC
Labels: bug
