### ISSUE TITLE
Install iOS ipa files on real devices via the UI

### ISSUE THREAD

**Issue by shamanec** [zebrunner/stf#133] opened 2020-03-13 12:54 UTC
**Is your feature request related to a problem? Please describe.**
Manual QA specialists using the STF can easily install an apk file to Android device via the STF UI and start testing. For iOS devices it is not possible to install *.ipa files and it takes some effort to somehow distribute it via AppCenter or HockeyApp or Beta by Crashlytics

**Describe the solution you'd like**
It should be possible to install *.ipa files directly to iOS real devices via the UI. 

**Describe alternatives you've considered**
There should be a possible but maybe not perfect solution since the STF host might not be on the same machine as the iOS device provider. Maybe mapping a drive on the STF host to the iOS provider machine and uploading the builds there and then using ideviceinstaller or ios-deploy on the provider itself to push it to a device but I am not sure how would the connection be made.

**Additional context**
N/A

**Comment by vdelendik** [comment] 2021-12-10 19:29
closing as duplicate of https://github.com/zebrunner/stf/issues/244 where we are going to reuse benefits of go-ios to upload install ipa application

**Closed by vdelendik** 2021-12-10 19:29 UTC
Labels: enhancement
