### ISSUE TITLE
error: device unauthorized. This adb server's $ADB_VENDOR_KEYS is not set Try 'adb kill-server' if that seems wrong

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#937] opened 2024-04-02 06:56 UTC
The error is reproduced with  android devices on 14 os
**Workaroud**- device is available after restart
**Log:** 
```

Connection to stf-triproxy-dev 7250 port [tcp/*] succeeded!
Connection to rethinkdb 28015 port [tcp/*] succeeded!
2024-04-02T06:02:40.025Z INF/provider 32 [*] Subscribing to permanent channel "o4c30cOrSA6DqyWJjx3cog=="
2024-04-02T06:02:40.031Z INF/db 32 [*] Connecting to rethinkdb:28015
2024-04-02T06:02:40.033Z INF/provider 32 [*] Sending output to "tcp://stf-triproxy-dev:7270"
2024-04-02T06:02:40.033Z INF/provider 32 [*] Receiving input from "tcp://stf-triproxy-dev:7250"
2024-04-02T06:02:40.034Z FTL/provider 32 [*] Adb client error Error: getaddrinfo EAI_AGAIN appium
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:82:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'appium'
}
2024-04-02T06:02:40.036Z FTL/util:lifecycle 32 [*] Shutting down due to fatal error with optional error :  undefined
Exit status: 1
```

**Appium log:** 

```
WARN Appium Driver "uiautomator2" has 1 potential problem: 
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.2.2) due to its peer dependency on older Appium v^2.4.1. Please upgrade `appium-uiautomator2-driver` to v3.0.5 or newer.
✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
04-01 21:05:12.912    78    78 I adb     : auth.cpp:416 adb_auth_init...
04-01 21:05:12.912    78    78 I adb     : auth.cpp:152 loaded new key from '/root/.android/adbkey' with fingerprint 24868D008D32488A8CD2E77FDEF8B60E04C5D63B3E67A21C0E52824C391E1A85
04-01 21:05:12.912    78    78 I adb     : auth.cpp:391 adb_auth_inotify_init...
04-01 21:05:12.912    78    85 I adb     : transport.cpp:335 RF.........8ZF: read thread spawning
04-01 21:05:12.912    78    86 I adb     : transport.cpp:307 RFC...........ZF: write thread spawning
04-01 21:05:12.920    78    78 I adb     : transport.cpp:1734 fetching keys for transport RFCW10R58ZF
04-01 21:05:12.920    78    78 I adb     : auth.cpp:468 Calling send_auth_response
04-01 21:05:12.932    78    78 I adb     : auth.cpp:435 Calling send_auth_publickey
state: error: device unauthorized. This adb server's $ADB_VENDOR_KEYS is not set Try 'adb kill-server' if that seems wrong. Otherwise check for a confirmation dialog on your device.

Authorize device manually!
Exiting without restarting...

```

**Comment by vdelendik** [comment] 2024-09-16 15:22
closing as not a bug. if we see `device unauthorized` then the only way -> reconnect and manually trust again.

**Closed by vdelendik** 2024-09-16 15:22 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2024-09-17 08:59
Closed
